name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Create native image with jpackage
        run: ./gradlew jpackage

      - name: Upload Shaded JAR
        uses: actions/upload-artifact@v3
        with:
          name: shaded-jar
          path: build/libs/*.jar

      - name: Upload Native Image
        uses: actions/upload-artifact@v3
        with:
          name: native-image
          path: build/jpackage/*
